FROM pyslam-g2o-pangolin

WORKDIR /

# RUN apt-get update && \
# 	apt-get upgrade -y && \
# 	apt-get install -y wget vim bzip2 git cmake libeigen3-dev

# RUN apt-get install libsuitesparse-dev 
# RUN apt-get install qtdeclarative5-dev 
# RUN apt-get install qt5-qmake 
# RUN apt-get install -y libqglviewer-dev

# RUN apt-get install libegl1-mesa-dev
# RUN apt install ffmpeg libavcodec-dev libavutil-dev libavformat-dev libswscale-dev libavdevice-dev

#for pangolin:
# RUN apt-get install libglew-dev
# RUN apt install ffmpeg libavcodec-dev libavutil-dev libavformat-dev libswscale-dev libavdevice-dev
# RUN pip install PyOpenGL PyOpenGL_accelerate

# RUN wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
# 	bash ~/miniconda.sh -b -p /opt/conda && \
# 	rm ~/miniconda.sh

# ENV PATH /opt/conda/bin:$PATH

# RUN conda update conda -y
# COPY environment.yml .
# RUN conda env create -f environment.yml
# RUN conda activate opencv

# RUN git clone https://github.com/uoip/g2opy.git ../g2opy
# WORKDIR "../g2opy"
# RUN mkdir build
# WORKDIR ""